In [1]:
import pandas as pd  # NX2UpxC?.RzST6t

In [49]:
df = pd.read_csv('survey_results_public.csv',index_col='Respondent') #不用默认的0123 用repsondent的值作为每一行的index，列数减少一个

In [50]:
df

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [4]:
df.describe()

,Respondent,CompTotal,ConvertedComp,WorkWeekHrs,CodeRevHrs,Age
count,88883.000000,5.594500e+04,5.582300e+04,64503.000000,49790.000000,79210.000000
mean,44442.000000,5.519014e+11,1.271107e+05,42.127197,5.084308,30.336699
std,25658.456325,7.331926e+13,2.841523e+05,37.287610,5.513931,9.178390
min,1.000000,0.000000e+00,0.000000e+00,1.000000,0.000000,1.000000
25%,22221.500000,2.000000e+04,2.577750e+04,40.000000,2.000000,24.000000
50%,44442.000000,6.200000e+04,5.728700e+04,40.000000,4.000000,29.000000
75%,66662.500000,1.200000e+05,1.000000e+05,44.750000,6.000000,35.000000
max,88883.000000,1.000000e+16,2.000000e+06,4850.000000,99.000000,99.000000

In [51]:
df.shape

(88883, 84)

In [7]:
df.info

<bound method DataFrame.info of        Respondent                                         MainBranch Hobbyist  \
0               1             I am a student who is learning to code      Yes
1               2             I am a student who is learning to code       No
2               3  I am not primarily a developer, but I write co...      Yes
3               4                     I am a developer by profession       No
4               5                     I am a developer by profession      Yes
...           ...                                                ...      ...
88878       88377                                                NaN      Yes
88879       88601                                                NaN       No
88880       88802                                                NaN       No
88881       88816                                                NaN       No
88882       88863                                                NaN      Yes

                                             OpenSourcer  \
0                                                  Never
1                                Less than once per year
2                                                  Never
3                                                  Never
4                             Once a month or more often
...                                                  ...
88878  Less than once a month but more than once per ...
88879                                              Never
88880                                              Never
88881                                              Never
88882                            Less than once per year

                                              OpenSource  \
0      The quality of OSS and closed source software ...
1      The quality of OSS and closed source software ...
2      The quality of OSS and closed source software ...
3      The quality of OSS and closed source software ...
4      OSS is, on average, of HIGHER quality than pro...
...                                                  ...
88878  The quality of OSS and closed source software ...
88879  The quality of OSS and closed source software ...
88880                                                NaN
88881  OSS is, on average, of HIGHER quality than pro...
88882  OSS is, on average, of HIGHER quality than pro...

                                              Employment  \
0                 Not employed, and not looking for work
1                     Not employed, but looking for work
2                                     Employed full-time
3                                     Employed full-time
4                                     Employed full-time
...                                                  ...
88878             Not employed, and not looking for work
88879                                                NaN
88880                                 Employed full-time
88881  Independent contractor, freelancer, or self-em...
88882             Not employed, and not looking for work

                      Country         Student  \
0              United Kingdom              No
1      Bosnia and Herzegovina  Yes, full-time
2                    Thailand              No
3               United States              No
4                     Ukraine              No
...                       ...             ...
88878                  Canada              No
88879                     NaN             NaN
88880                     NaN             NaN
88881                     NaN             NaN
88882                   Spain  Yes, full-time

                                                 EdLevel  \
0                              Primary/elementary school
1      Secondary school (e.g. American high school, G...
2               Bachelor’s degree (BA, BS, B.Eng., etc.)
3               Bachelor’s degree (BA, BS, B.Eng., etc.)
4               Bachelor’s degree (BA, BS, B.Eng., etc.)
...                                                  ...
88878                          Primary/elementary school
88879                                                NaN
88880                                                NaN
88881                                                NaN
88882                 Professional degree (JD, MD, etc.)

                                          UndergradMajor  ...  \
0                                                    NaN  ...
1                                                    NaN  ...
2                          Web development or web design  ...
3      Computer science, computer engineering, or sof...  ...
4      Computer science, computer engineering, or sof...  ...
...                                                  ...  ...
88878                                                NaN  ...
88879                                                NaN  ...
88880                                                NaN  ...
88881                                                NaN  ...
88882  Computer science, computer engineering, or sof...  ...

                                  WelcomeChange  \
0       Just as welcome now as I felt last year
1       Just as welcome now as I felt last year
2       Just as welcome now as I felt last year
3       Just as welcome now as I felt last year
4       Just as welcome now as I felt last year
...                                         ...
88878                                       NaN
88879                                       NaN
88880                                       NaN
88881                                       NaN
88882  Somewhat less welcome now than last year

                                            SONewContent   Age Gender Trans  \
0      Tech articles written by other developers;Indu...  14.0    Man    No
1      Tech articles written by other developers;Indu...  19.0    Man    No
2      Tech meetups or events in your area;Courses on...  28.0    Man    No
3      Tech articles written by other developers;Indu...  22.0    Man    No
4      Tech meetups or events in your area;Courses on...  30.0    Man    No
...                                                  ...   ...    ...   ...
88878  Tech articles written by other developers;Tech...   NaN    Man    No
88879                                                NaN   NaN    NaN   NaN
88880                                                NaN   NaN    NaN   NaN
88881                                                NaN   NaN    NaN   NaN
88882  Tech articles written by other developers;Indu...  18.0    Man    No

                     Sexuality  \
0      Straight / Heterosexual
1      Straight / Heterosexual
2      Straight / Heterosexual
3      Straight / Heterosexual
4      Straight / Heterosexual
...                        ...
88878                      NaN
88879                      NaN
88880                      NaN
88881                      NaN
88882  Straight / Heterosexual

                                               Ethnicity Dependents  \
0                                                    NaN         No
1                                                    NaN         No
2                                                    NaN        Yes
3                           White or of European descent         No
4               White or of European descent;Multiracial         No
...                                                  ...        ...
88878                                                NaN         No
88879                                                NaN        NaN
88880                                                NaN        NaN
88881                                                NaN        NaN
88882  Hispanic or Latino/Latina;White or of European...         No

                SurveyLength                  SurveyEase
0      Appropriate in length  Neither easy nor difficult
1      Appropriate in length  Neither easy nor difficult
2      Appropriate in length  Neither easy nor difficult
3      Appropriate in length                        Easy
4      Appropriate in length                        Easy
...                      ...                         ...
88878  Appropriate in length                        Easy
88879                    NaN                         NaN
88880                    NaN                         NaN
88881                    NaN                         NaN
88882  Appropriate in length                        Easy

[88883 rows x 85 columns]>

In [ ]:
pd.set_option('display.max_columns',85) # set how many columns will be display

In [52]:
schema_df = pd.read_csv('survey_results_schema.csv',index_col='Column')

In [53]:
schema_df

                                                   QuestionText
Column
Respondent    Randomized respondent ID number (not in order ...
MainBranch    Which of the following options best describes ...
Hobbyist                                Do you code as a hobby?
OpenSourcer         How often do you contribute to open source?
OpenSource    How do you feel about the quality of open sour...
...                                                         ...
Sexuality     Which of the following do you currently identi...
Ethnicity     Which of the following do you identify as? Ple...
Dependents    Do you have any dependents (e.g., children, el...
SurveyLength  How do you feel about the length of the survey...
SurveyEase    How easy or difficult was this survey to compl...

[85 rows x 1 columns]

In [55]:
schema_df.loc['MgrIdiot'] #直接用列名查询

QuestionText    How confident are you that your manager knows ...
Name: MgrIdiot, dtype: object

In [58]:
schema_df.loc['MgrIdiot','QuestionText']

'How confident are you that your manager knows what they’re doing?'

In [59]:
schema_df.sort_index(inplace=True) # ascending=False倒序

                                                    QuestionText
Column
Age            What is your age (in years)? If you prefer not...
Age1stCode     At what age did you write your first line of c...
BetterLife     Do you think people born today will have a bet...
BlockchainIs   Blockchain / cryptocurrency technology is prim...
BlockchainOrg  How is your organization thinking about or imp...
...                                                          ...
WorkPlan                 How structured or planned is your work?
WorkRemote                       How often do you work remotely?
WorkWeekHrs     On average, how many hours per week do you work?
YearsCode      Including any education, how many years have y...
YearsCodePro   How many years have you coded professionally (...

[85 rows x 1 columns]

In [ ]:
# to show all rows or the first 20 rows
pd.set_option('display.max_rows',20)

In [10]:
df['Student']

0                    No
1        Yes, full-time
2                    No
3                    No
4                    No
              ...
88878                No
88879               NaN
88880               NaN
88881               NaN
88882    Yes, full-time
Name: Student, Length: 88883, dtype: object

In [17]:
type(df['Student'][0])

str

In [18]:
df['Student'][0].lower()

'no'

In [19]:
df.head() #first 5 rows

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [20]:
df.head(10)

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
5,6,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Canada,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Mathematics or statistics,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,28.0,Man,No,Straight / Heterosexual,East Asian,No,Too long,Neither easy nor difficult
6,7,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",...,A lot more welcome now than last year,NaN,42.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Neither easy nor difficult
7,8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,NaN,Appropriate in length,Neither easy nor difficult
8,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,23.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
9,10,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,...,Somewhat less welcome now than last year,Tech articles written by other developers;Tech...,NaN,NaN,NaN,NaN,NaN,Yes,Too long,Difficult

In [21]:
df.tail() # last 5 rows

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [62]:
# 改变 列名
df.rename(columns={'ConvertedComp':'SalaryUSD'}, inplace = True)

In [63]:
df['SalaryUSD']

Respondent
1            NaN
2            NaN
3         8820.0
4        61000.0
5            NaN
          ...
88377        NaN
88601        NaN
88802        NaN
88816        NaN
88863        NaN
Name: SalaryUSD, Length: 88883, dtype: float64

In [64]:
df['Hobbyist']

Respondent
1        Yes
2         No
3        Yes
4         No
5        Yes
        ...
88377    Yes
88601     No
88802     No
88816     No
88863    Yes
Name: Hobbyist, Length: 88883, dtype: object

In [65]:
df['Hobbyist'].map({'Yes': True,'No': False})

Respondent
1         True
2        False
3         True
4        False
5         True
         ...
88377     True
88601    False
88802    False
88816    False
88863     True
Name: Hobbyist, Length: 88883, dtype: bool

In [66]:
df['Hobbyist'] = df['Hobbyist'].map({'Yes': True,'No': False})

In [67]:
df['Hobbyist']

Respondent
1         True
2        False
3         True
4        False
5         True
         ...
88377     True
88601    False
88802    False
88816    False
88863     True
Name: Hobbyist, Length: 88883, dtype: bool

In [71]:
df.columns

Index(['MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource', 'Employment',
       'Country', 'Student', 'EdLevel', 'UndergradMajor', 'EduOther',
       'OrgSize', 'DevType', 'YearsCode', 'Age1stCode', 'YearsCodePro',
       'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney', 'MgrWant', 'JobSeek',
       'LastHireDate', 'LastInt', 'FizzBuzz', 'JobFactors', 'ResumeUpdate',
       'CurrencySymbol', 'CurrencyDesc', 'CompTotal', 'CompFreq', 'SalaryUSD',
       'WorkWeekHrs', 'WorkPlan', 'WorkChallenge', 'WorkRemote', 'WorkLoc',
       'ImpSyn', 'CodeRev', 'CodeRevHrs', 'UnitTests', 'PurchaseHow',
       'PurchaseWhat', 'LanguageWorkedWith', 'LanguageDesireNextYear',
       'DatabaseWorkedWith', 'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='object')

In [72]:
df.sort_values(by=['Country','SalaryUSD'], ascending=[True,False],inplace=True)

In [74]:
df[['Country','SalaryUSD']].head(15)

                Country  SalaryUSD
Respondent
63129       Afghanistan  1000000.0
50499       Afghanistan   153216.0
39258       Afghanistan    19152.0
58450       Afghanistan    17556.0
7085        Afghanistan    14364.0
22450       Afghanistan     7980.0
48436       Afghanistan     4464.0
10746       Afghanistan     3996.0
8149        Afghanistan     1596.0
29736       Afghanistan     1116.0
28638       Afghanistan        0.0
722         Afghanistan        0.0
85715       Afghanistan        NaN
50767       Afghanistan        NaN
2782        Afghanistan        NaN

In [75]:
df['SalaryUSD'].nlargest(10)

Respondent
25983    2000000.0
87896    2000000.0
22013    2000000.0
28243    2000000.0
72732    2000000.0
78151    2000000.0
80200    2000000.0
52132    2000000.0
75561    2000000.0
32250    2000000.0
Name: SalaryUSD, dtype: float64

In [76]:
df.nlargest(10,'SalaryUSD')

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
25983,I am a developer by profession,True,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Canada,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,...,Just as welcome now as I felt last year,NaN,24.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
87896,I am a developer by profession,True,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,Germany,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,32.0,Man,No,Gay or Lesbian,White or of European descent,No,Appropriate in length,Neither easy nor difficult
22013,I am a developer by profession,True,Never,The quality of OSS and closed source software ...,Employed full-time,India,No,"Professional degree (JD, MD, etc.)","A natural science (ex. biology, chemistry, phy...",Taken an online course in programming or softw...,...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,NaN,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Easy
28243,I am a developer by profession,True,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,A lot less welcome now than last year,Tech meetups or events in your area,NaN,NaN,NaN,Straight / Heterosexual,NaN,Yes,Too short,Easy
72732,"I am not primarily a developer, but I write co...",False,Less than once a month but more than once per ...,"OSS is, on average, of LOWER quality than prop...",NaN,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Contributed to open source software,...,A lot less welcome now than last year,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,Yes,Too long,Easy
78151,I am a developer by profession,True,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Mexico,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,32.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina,No,Appropriate in length,Easy
80200,I am a developer by profession,True,Never,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Netherlands,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,...,NaN,Tech articles written by other developers,25.0,Woman,No,Bisexual,White or of European descent,No,Appropriate in length,Easy
52132,I am a developer by profession,True,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Peru,No,Some college/university study without earning ...,I never declared a major,Completed an industry certification program (e...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,48.0,Man,NaN,NaN,Black or of African descent;East Asian;Hispani...,Yes,Appropriate in length,Easy
75561,I am a developer by profession,True,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Singapore,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A humanities discipline (ex. literature, histo...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech meetups or events in your area,37.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
32250,I am a developer by profession,True,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,Switzerland,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken a part-time in-person course in programm...,...,Just as welcome now as I felt last year,Industry news about technologies you're intere...,30.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy

In [77]:
df.nsmallest(10,'SalaryUSD')

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
28638,I am a developer by profession,True,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",Afghanistan,NaN,"Other doctoral degree (Ph.D, Ed.D., etc.)",I never declared a major,NaN,...,A lot less welcome now than last year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,NaN
722,I am a developer by profession,False,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,NaN,Afghanistan,NaN,NaN,NaN,NaN,...,Not applicable - I did not use Stack Overflow ...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,Too long,Difficult
13825,I am a developer by profession,True,Never,The quality of OSS and closed source software ...,NaN,Algeria,NaN,NaN,NaN,NaN,...,A lot less welcome now than last year,NaN,56.0,NaN,NaN,NaN,NaN,Yes,Too short,Easy
40913,I am a developer by profession,True,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,Armenia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers,22.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Easy
30630,I am a developer by profession,True,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Australia,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,Taken an online course in programming or softw...,...,A lot less welcome now than last year,NaN,43.0,NaN,No,NaN,NaN,No,Appropriate in length,Easy
69049,I am a developer by profession,False,Never,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Australia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,...,Just as welcome now as I felt last year,NaN,34.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
19340,"I am not primarily a developer, but I write co...",True,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",NaN,Austria,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",Fine arts or performing arts (ex. graphic desi...,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,NaN,32.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
16214,"I am not primarily a developer, but I write co...",True,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Bangladesh,"Yes, part-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)","A natural science (ex. biology, chemistry, phy...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Cour...,99.0,NaN,No,NaN,NaN,NaN,Too long,Easy
29355,I am a developer by profession,True,Never,"OSS is, on average, of LOWER quality than prop...","Independent contractor, freelancer, or self-em...",Bosnia and Herzegovina,"Yes, part-time",Some college/university study without earning ...,"Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,NaN,No,NaN,NaN,NaN,Too long,Easy
1685,I am a developer by profession,True,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Brazil,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Neither easy nor difficult

In [3]:
df['SalaryUSD'].head(15)

NameError: name 'df' is not defined

In [23]:
# convert dictionary into dataframe
people = {
    'first':['John','Ethan','Walter'],
    'last':['Smith','Tai','Disney'],
    'email':['john.smith@gmail.com', 'ethantai@gmail.com','walterdisney@gmail.com']
    }
dataframe = pd.DataFrame(people)

dataframe

    first    last                   email
0    John   Smith    john.smith@gmail.com
1   Ethan     Tai      ethantai@gmail.com
2  Walter  Disney  walterdisney@gmail.com

In [25]:
type(dataframe['email'])  # Series-- 1D array, a row of data with more functions

pandas.core.series.Series

In [26]:
dataframe.email

0      john.smith@gmail.com
1        ethantai@gmail.com
2    walterdisney@gmail.com
Name: email, dtype: object

In [27]:
dataframe[['first','last']] #receive a list as parameter, all column names in the list

    first    last
0    John   Smith
1   Ethan     Tai
2  Walter  Disney

In [28]:
dataframe.columns

Index(['first', 'last', 'email'], dtype='object')

In [29]:
dataframe.iloc[0] # check specific row, integer location用数字表示位置

first                    John
last                    Smith
email    john.smith@gmail.com
Name: 0, dtype: object

In [30]:
dataframe.iloc[[0,1]] # select two rows

   first   last                 email
0   John  Smith  john.smith@gmail.com
1  Ethan    Tai    ethantai@gmail.com

In [31]:
dataframe.iloc[[0,1],2] # select two rows, the 3rd column

0    john.smith@gmail.com
1      ethantai@gmail.com
Name: email, dtype: object

In [32]:
dataframe.loc[0] #loc用label定位，行有index0，1，2，3作为integer用

first                    John
last                    Smith
email    john.smith@gmail.com
Name: 0, dtype: object

In [34]:
dataframe.loc[[0,1],'email'] #列用名称

0    john.smith@gmail.com
1      ethantai@gmail.com
Name: email, dtype: object

In [35]:
dataframe.loc[[0,1],['email','last']] # 顺序Matters

                  email   last
0  john.smith@gmail.com  Smith
1    ethantai@gmail.com    Tai

In [37]:
dataframe['first'].value_counts()  #对该列中的数据进行统计

John      1
Ethan     1
Walter    1
Name: first, dtype: int64

In [40]:
dataframe.loc[0:2,'first':'email']

    first    last                   email
0    John   Smith    john.smith@gmail.com
1   Ethan     Tai      ethantai@gmail.com
2  Walter  Disney  walterdisney@gmail.com

In [ ]:
# use unique column as index in stead of 0,1,2,3..

In [41]:
dataframe.set_index('email')  # use email as index, 暂时的 不改变原数据结构

                         first    last
email
john.smith@gmail.com      John   Smith
ethantai@gmail.com       Ethan     Tai
walterdisney@gmail.com  Walter  Disney

In [42]:
dataframe

    first    last                   email
0    John   Smith    john.smith@gmail.com
1   Ethan     Tai      ethantai@gmail.com
2  Walter  Disney  walterdisney@gmail.com

In [43]:
dataframe.set_index('email', inplace=True) #改变原数据结构

In [44]:
dataframe

                         first    last
email
john.smith@gmail.com      John   Smith
ethantai@gmail.com       Ethan     Tai
walterdisney@gmail.com  Walter  Disney

In [45]:
dataframe.index

Index(['john.smith@gmail.com', 'ethantai@gmail.com', 'walterdisney@gmail.com'], dtype='object', name='email')

In [46]:
dataframe.loc['walterdisney@gmail.com']

first    Walter
last     Disney
Name: walterdisney@gmail.com, dtype: object

In [47]:
dataframe.reset_index(inplace=True) # reset

In [48]:
dataframe

                    email   first    last
0    john.smith@gmail.com    John   Smith
1      ethantai@gmail.com   Ethan     Tai
2  walterdisney@gmail.com  Walter  Disney

In [ ]:
bargain_idx = (reviews.points / reviews.price).idxmax()
bargain_wine = reviews.loc[bargain_idx, 'title']

In [ ]:
grp = df.groupby('Name') 
grp.get_group('subgroup name')

for name,value in grp:
    print(name)
    print(value)
    
grp.agg({'Age' : 'sum', 'Score' : 'std'})