In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('ETH_1h.csv')

In [4]:
df.head()

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71

In [18]:
df.loc[0,'Date']

Timestamp('2020-03-13 20:00:00')

In [10]:
df['Date'] = pd.to_datetime(df['Date'],format='%Y-%m-%d %I-%p')

In [11]:
df['Date']

0       2020-03-13 20:00:00
1       2020-03-13 19:00:00
2       2020-03-13 18:00:00
3       2020-03-13 17:00:00
4       2020-03-13 16:00:00
                ...
23669   2017-07-01 15:00:00
23670   2017-07-01 14:00:00
23671   2017-07-01 13:00:00
23672   2017-07-01 12:00:00
23673   2017-07-01 11:00:00
Name: Date, Length: 23674, dtype: datetime64[ns]

In [12]:
df.loc[0,'Date'].day_name()

'Friday'

In [14]:
d_parser = lambda x: pd.datetime.strptime(x,'%Y-%m-%d %I-%p')
df = pd.read_csv('ETH_1h.csv', parse_dates=['Date'], date_parser=d_parser)

<ipython-input-14-7500f672de7f>:1: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  d_parser = lambda x: pd.datetime.strptime(x,'%Y-%m-%d %I-%p')

In [19]:
df.head()

                 Date  Symbol    Open    High     Low   Close      Volume
0 2020-03-13 20:00:00  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1 2020-03-13 19:00:00  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2 2020-03-13 18:00:00  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3 2020-03-13 17:00:00  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4 2020-03-13 16:00:00  ETHUSD  124.85  129.51  120.17  124.08  4461424.71

In [20]:
# only see data in 2020
filt = df['Date']>='2020'
df[filt]

                    Date  Symbol    Open    High     Low   Close      Volume
0    2020-03-13 20:00:00  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1    2020-03-13 19:00:00  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2    2020-03-13 18:00:00  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3    2020-03-13 17:00:00  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4    2020-03-13 16:00:00  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                  ...     ...     ...     ...     ...     ...         ...
1744 2020-01-01 04:00:00  ETHUSD  129.57  130.00  129.50  129.56   702786.82
1745 2020-01-01 03:00:00  ETHUSD  130.37  130.44  129.38  129.57   496704.23
1746 2020-01-01 02:00:00  ETHUSD  130.14  130.50  129.91  130.37   396315.72
1747 2020-01-01 01:00:00  ETHUSD  128.34  130.14  128.32  130.14   635419.40
1748 2020-01-01 00:00:00  ETHUSD  128.54  128.54  128.12  128.34   245119.91

[1749 rows x 7 columns]

In [21]:
# only see data in 2019
filt = (df['Date']>='2019') & (df['Date']<'2020')
df[filt]

                     Date  Symbol    Open    High     Low   Close      Volume
1749  2019-12-31 23:00:00  ETHUSD  128.33  128.69  128.14  128.54   440678.91
1750  2019-12-31 22:00:00  ETHUSD  128.38  128.69  127.95  128.33   554646.02
1751  2019-12-31 21:00:00  ETHUSD  127.86  128.43  127.72  128.38   350155.69
1752  2019-12-31 20:00:00  ETHUSD  127.84  128.34  127.71  127.86   428183.38
1753  2019-12-31 19:00:00  ETHUSD  128.69  128.69  127.60  127.84  1169847.84
...                   ...     ...     ...     ...     ...     ...         ...
10504 2019-01-01 04:00:00  ETHUSD  130.75  133.96  130.74  131.96  2791135.37
10505 2019-01-01 03:00:00  ETHUSD  130.06  130.79  130.06  130.75   503732.63
10506 2019-01-01 02:00:00  ETHUSD  130.79  130.88  129.55  130.06   838183.43
10507 2019-01-01 01:00:00  ETHUSD  131.62  131.62  130.77  130.79   434917.99
10508 2019-01-01 00:00:00  ETHUSD  130.53  131.91  130.48  131.62  1067136.21

[8760 rows x 7 columns]

In [45]:
df['Date']

KeyError: 'Date'

In [46]:
# see some day's data
df.set_index('Date', inplace=True)
df

KeyError: "None of ['Date'] are in the columns"

In [32]:
df['2020']

                     Symbol    Open    High     Low   Close      Volume
Date
2020-03-13 20:00:00  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
2020-03-13 19:00:00  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2020-03-13 18:00:00  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
2020-03-13 17:00:00  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
2020-03-13 16:00:00  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                     ...     ...     ...     ...     ...         ...
2020-01-01 04:00:00  ETHUSD  129.57  130.00  129.50  129.56   702786.82
2020-01-01 03:00:00  ETHUSD  130.37  130.44  129.38  129.57   496704.23
2020-01-01 02:00:00  ETHUSD  130.14  130.50  129.91  130.37   396315.72
2020-01-01 01:00:00  ETHUSD  128.34  130.14  128.32  130.14   635419.40
2020-01-01 00:00:00  ETHUSD  128.54  128.54  128.12  128.34   245119.91

[1749 rows x 6 columns]

In [33]:
df['2020-01-01']

                     Symbol    Open    High     Low   Close      Volume
Date
2020-01-01 23:00:00  ETHUSD  129.77  130.27  129.24  130.19   215362.64
2020-01-01 22:00:00  ETHUSD  131.41  131.41  129.36  129.77   411940.73
2020-01-01 21:00:00  ETHUSD  131.73  131.99  130.97  131.41  1168999.08
2020-01-01 20:00:00  ETHUSD  131.34  131.87  131.23  131.73   162346.84
2020-01-01 19:00:00  ETHUSD  131.64  131.72  131.15  131.34   167992.84
2020-01-01 18:00:00  ETHUSD  131.97  132.14  131.24  131.64   266693.21
2020-01-01 17:00:00  ETHUSD  132.55  132.68  131.94  131.97   244271.72
2020-01-01 16:00:00  ETHUSD  131.75  132.56  131.51  132.55   270425.94
2020-01-01 15:00:00  ETHUSD  131.66  132.15  131.29  131.75   168230.71
2020-01-01 14:00:00  ETHUSD  131.41  132.05  130.93  131.66   143192.12
2020-01-01 13:00:00  ETHUSD  131.28  132.08  131.04  131.41   569499.97
2020-01-01 12:00:00  ETHUSD  130.36  131.31  130.36  131.28   221073.63
2020-01-01 11:00:00  ETHUSD  130.33  131.42  130.23  130.36   243130.52
2020-01-01 10:00:00  ETHUSD  129.98  130.33  129.88  130.33    73422.13
2020-01-01 09:00:00  ETHUSD  130.01  130.22  129.96  129.98   108011.54
2020-01-01 08:00:00  ETHUSD  129.87  130.01  129.61  130.01   134231.17
2020-01-01 07:00:00  ETHUSD  130.00  130.25  129.80  129.87   112620.14
2020-01-01 06:00:00  ETHUSD  129.83  130.25  129.82  130.00   118328.64
2020-01-01 05:00:00  ETHUSD  129.56  129.94  129.47  129.83   232163.70
2020-01-01 04:00:00  ETHUSD  129.57  130.00  129.50  129.56   702786.82
2020-01-01 03:00:00  ETHUSD  130.37  130.44  129.38  129.57   496704.23
2020-01-01 02:00:00  ETHUSD  130.14  130.50  129.91  130.37   396315.72
2020-01-01 01:00:00  ETHUSD  128.34  130.14  128.32  130.14   635419.40
2020-01-01 00:00:00  ETHUSD  128.54  128.54  128.12  128.34   245119.91

In [35]:
df['2020-01-01'].['High'].max()

132.68

In [41]:
# reorganize in Days, get maximum number
highs = df['High'].resample('D').max()

In [42]:
highs['2020-01-01']

132.68

In [43]:
# reorganize the data frame in days, get max number
df.resample('D').max()

            Symbol    Open    High     Low   Close       Volume
Date
2017-07-01  ETHUSD  279.98  279.99  272.10  275.01   5396852.35
2017-07-02  ETHUSD  292.54  293.73  284.87  292.54   7081816.11
2017-07-03  ETHUSD  285.00  285.00  280.60  282.36   3485745.42
2017-07-04  ETHUSD  282.58  282.83  282.31  282.58   4874310.69
2017-07-05  ETHUSD  271.00  274.97  269.25  271.00   6082287.50
...            ...     ...     ...     ...     ...          ...
2020-03-09  ETHUSD  207.79  208.65  205.83  207.79   9973969.49
2020-03-10  ETHUSD  205.79  206.28  203.02  205.79   4273768.87
2020-03-11  ETHUSD  202.48  202.98  201.35  202.48   7425363.13
2020-03-12  ETHUSD  194.61  195.64  192.02  193.44  19731142.71
2020-03-13  ETHUSD  134.03  148.00  128.99  134.03  19431820.56

[987 rows x 6 columns]

In [47]:
%matplotlib inline
highs.plot()

ModuleNotFoundError: No module named 'matplotlib'

In [48]:
df.resample('W').mean()

                  Open        High         Low       Close        Volume
Date
2017-07-02  268.066486  271.124595  264.819730  268.202162  2.185035e+06
2017-07-09  261.337024  262.872917  259.186190  261.062083  1.337349e+06
2017-07-16  196.193214  199.204405  192.722321  195.698393  2.986756e+06
2017-07-23  212.351429  215.779286  209.126310  212.783750  4.298593e+06
2017-07-30  203.496190  205.110357  201.714048  203.309524  1.581729e+06
...                ...         ...         ...         ...           ...
2020-02-16  255.021667  257.255238  252.679762  255.198452  2.329087e+06
2020-02-23  265.220833  267.263690  262.948512  265.321905  1.826094e+06
2020-03-01  236.720536  238.697500  234.208750  236.373988  2.198762e+06
2020-03-08  229.923571  231.284583  228.373810  229.817619  1.628910e+06
2020-03-15  176.937521  179.979487  172.936239  176.332821  4.259828e+06

[142 rows x 5 columns]

In [49]:
df.resample('W').agg({'Close':'mean','High':'max','Low':'min','Volume':'sum'})

                 Close    High     Low        Volume
Date
2017-07-02  268.202162  293.73  253.23  8.084631e+07
2017-07-09  261.062083  285.00  231.25  2.246746e+08
2017-07-16  195.698393  240.33  130.26  5.017750e+08
2017-07-23  212.783750  249.40  153.25  7.221637e+08
2017-07-30  203.309524  229.99  178.03  2.657305e+08
...                ...     ...     ...           ...
2020-02-16  255.198452  290.00  216.31  3.912867e+08
2020-02-23  265.321905  287.13  242.36  3.067838e+08
2020-03-01  236.373988  278.13  209.26  3.693920e+08
2020-03-08  229.817619  253.01  196.00  2.736569e+08
2020-03-15  176.332821  208.65   90.00  4.983998e+08

[142 rows x 4 columns]